#######################################################################################
################### A General Tool for Living Meta-Analysis #######################
#######################################################################################
# v.1.3 2026.07.19

###################   Shiny App UI ###################################

# Define UI
ui <- fluidPage(theme = shinytheme("cosmo"),
                tags$head(
                  tags$meta(charset = "UTF-8")
                ),
                useShinyjs(),
                titlePanel(title = div("A General Tool for Living Meta-Analysis (updated)"),
                           windowTitle = "A General Tool for Living Meta-Analysis (updated)"),
                sidebarLayout(
                  sidebarPanel(fluidRow(
                    uiOutput("currentDataFile"),
                    actionButton("recalculateButton","(Re)Calculate Meta-Analysis", icon("sync"),
                                 style = "color: yellow; background-color: green; margin-bottom: 10px",
                                 disabled = TRUE
                                 ),

                    tabsetPanel(id = "dataSetupPanel", selected = "Study criteria",
                      tabPanel("Load Data File",
                               br(),
                               fileInput("DataFileUp", label = "Upload your data file (.csv .xls or .xlsx)", accept = c(".xls", ".xlsx", ".csv")),
                               uiOutput("inputFileError"),
                               uiOutput("curatedDataChooser"),
                               p("Loading a data file replaces the current data.",
                                 'To verify the change, keep the "Current data" or "Included Studies" tab',
                                 'open on the right, and press "(Re)Calculate Meta-Analysis"',
                                 'after loading.'),
                               hr(),
                               p(tags$strong("Selection settings")),
                               p('Save every left-panel selection (study criteria, moderator choice,',
                                 'and prior specifications), plus the Descriptives-tab table choices,',
                                 'to a file, or load a previously saved file to restore those selections.',
                                 'Load the matching data file first, then the selections file, and press',
                                 '"(Re)Calculate Meta-Analysis" afterwards.'),
                               downloadButton("selectionsDown", "Save current selections (.json)"),
                               br(), br(),
                               fileInput("SelectionsUp", label = NULL,
                                         buttonLabel = "Load selections...",
                                         accept = ".json"),
                               p(tags$small('To make a copy of this app that starts up with particular',
                                            'selections (for example, the selections used in a published',
                                            'article), place a saved selections file at',
                                            tags$code("data/default_selections.json"),
                                            'in the app directory; it is applied automatically at startup.'))
                      ),
                      tabPanel("Study criteria",

                               ##########  The study selection panel is created in the server:
                               uiOutput("studyCriteria"),
                               ##########
                               tags$a(href="#currentDataFile", class="btn btn-default", "Go to top")
                               ),
                      tabPanel("Moderator Selection",
                               uiOutput("moderatorSelection_ui")
                      ),

                      tabPanel("Prior specifications",
                               br(), 
                               numericInput(inputId = "mupriormean", 
                                            label = p("µ prior mean",style="color:#333333",
                                                      tags$style(type = "text/css", "#q16 {vertical-align: top;}"),
                                                      bsButton("q16", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),   
                                            value = 0, step = 0.1),
                               bsPopover(id="q16", title = "µ prior mean.",
                                         content = paste0("<p>Set the mean of your µ prior (effect).",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Leaving BOTH the µ prior mean and SD fields empty gives an improper uniform prior for µ (Bayes factors and the robustness check then cannot be computed).",
                                                          "<p>Prior changes take effect at the next press of (Re)Calculate Meta-Analysis.",
                                                          "<p>Default: 0"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               numericInput(inputId = "mupriorsd", 
                                            label = p("µ prior standard deviation", style="color:#333333",
                                                      tags$style(type = "text/css", "#q17 {vertical-align: top;}"),
                                                      bsButton("q17", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            value = 1.5, step = 0.1, min = 0),
                               bsPopover(id="q17", title = "µ prior standard deviation.",
                                            content = paste0("<p>Set the standard deviation of your µ prior (effect).",
                                                             "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                             "<p>Leaving BOTH the µ prior mean and SD fields empty gives an improper uniform prior for µ (Bayes factors and the robustness check then cannot be computed).",
                                                             "<p>Prior changes take effect at the next press of (Re)Calculate Meta-Analysis.",
                                                             "<p>Default: 1.5"),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               radioButtons(inputId = "robust", 
                                            label = p("µ Bayes Factor robustness check", style="color:#333333",
                                                      tags$style(type = "text/css", "#q18 {vertical-align: top;}"),
                                                      bsButton("q18", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            choices = c(No = "No", Yes = "Yes")),
                               bsPopover(id="q18", title = "µ Bayes Factor robustness check.",
                                            content = paste0("<p>Bayes Factors over a variety of prior standard deviations will be plotted.",
                                                             "<p>Note that selecting Yes will lead to an increase in computation time and that the plot will only be computed if priors for τ and μ are proper.",
                                                             "<p>Default: No."),
                                            placement = "right", 
                                            trigger = "click",
                                            options = list(container = "body")),
                               radioButtons(inputId = "tauprior", 
                                            label = p("τ prior", style="color:#333333",
                                                      tags$style(type = "text/css", "#q19 {vertical-align: top;}"),
                                                      bsButton("q19", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            choices = c("Half cauchy", "Half normal","uniform", "sqrt", "Jeffreys", "BergerDeely", "conventional", "DuMouchel", "shrinkage", "I2")),
                               bsPopover(id="q19", title = "τ prior.",
                                         content = paste0("<p>Choose your τ prior.",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Only Half cauchy and Half normal are proper priors.  Bayes factors and the robustness check are only computed when the priors for both τ and µ are proper.",
                                                          "<p>Prior changes take effect at the next press of (Re)Calculate Meta-Analysis.",
                                                          "<p>Default: Half cauchy.",
                                                          "<p><small>Note: <em>Half normal</em> was labeled <em>Half student t</em> in earlier versions of this app ",
                                                          "(including the published Allbritton et al. and Wolf et al. versions); the fitted prior was always a half-normal ",
                                                          "distribution, so results are unchanged.</small>"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               numericInput(inputId="scaletau", 
                                            label = p("τ prior scale (for half cauchy or half normal)",style="color:#333333",
                                                      tags$style(type = "text/css", "#q20 {vertical-align: top;}"),
                                                      bsButton("q20", label = "", icon = icon("info"), style = "color: #fff; background-color: #337ab7; border-color: #2e6da4", size = "extra-small")),    
                                            value=0.5, step=0.05),
                               bsPopover(id="q20", title = "τ prior scale.",
                                         content = paste0("<p>Set the scale of your τ prior (if a half cauchy or a half normal prior is selected).",
                                                          "<p>Note that the results and their interpretability are drastically influenced by prior choices.",
                                                          "<p>Prior changes take effect at the next press of (Re)Calculate Meta-Analysis.",
                                                          "<p>Default: 0.5"),
                                         placement = "right", 
                                         trigger = "click",
                                         options = list(container = "body")),
                               a("Further information on choosing an appropriate τ prior.", href="https://cran.r-project.org/web/packages/bayesmeta/bayesmeta.pdf", target = "_blank")),
                      
                      
                      
                      
                      tabPanel("Add a Study",   
                               p("Add new studies here.  Each effect size from a multi-experiment or multi-measurement",
                                 "paper should be a separate entry.",
                                 'An alternative method for adding studies is to download "Current data including added',
                                 'studies" (.xlsx) from the "Downloads" tab, add new rows of data, then upload the new',
                                 'file in the "Load Data File" tab.'),
                               hr(),
                               
                               ##########  The rest of the study selection panel is created in the server:
                               uiOutput("studyAskType"),
                               uiOutput("setNewPaper"),
                               uiOutput("addStudies1"),
                               uiOutput("addStudies2"),
                               uiOutput("addStudies3"),
                               ##########
                      ),
                      
                      
                      
                      
                      
                      
                      
                      
                      ############ "Saved Bayesian Models" panel
                      tabPanel("Saved Plots and Models",   
                               p("The Bayesian models created by bayesmeta can take a long time to compute.",
                                 "To save time, you can download the Bayesian models and robustness plots computed",
                                 "in the current session and upload them in a future session.",
                                 "Uploaded models are added to the cache, so the matching analyses load instantly",
                                 "instead of asking for confirmation and recomputing.",
                                 "(Frequentist results compute quickly and are not saved here.)"
                               ),
                               hr(),
                               #
                               p(tags$strong("Bayesmeta models")),
                               
                               #
                               downloadButton("rds_file.bma", "Download Saved Models"),
                               fileInput("SavedModelsUp", label = "Upload Saved Models", accept = c(".rds", ".RDS", ".Rds")),
                               #
                               actionButton("ClearModels", "Delete Saved Models"),
                               #
                               #
                               hr(),
                               #
                               p(tags$strong("Bayes Factor Robustness Plots")),
                               
                               #
                               downloadButton("rds_file.robustnessPlots", "Download Saved Plots"),
                               fileInput("SavedPlotsUp", label = "Upload Saved Plots", accept = c(".rds", ".RDS", ".Rds")),
                               #
                               actionButton("ClearPlots", "Delete Saved Plots"),
                               #
                               hr(),
                               #
                               p(tags$strong("Bayesian meta-regression models")),
                               #
                               downloadButton("rds_file.bmr", "Download Saved Regression Models"),
                               fileInput("SavedBmrModelsUp", label = "Upload Saved Regression Models", accept = c(".rds", ".RDS", ".Rds")),
                               #
                               actionButton("ClearBmrModels", "Delete Saved Regression Models"),
                               #
                               hr(),
                               #
                               p(tags$strong("Bayesian multilevel models")),
                               #
                               downloadButton("rds_file.bml", "Download Saved Multilevel Models"),
                               fileInput("SavedBmlModelsUp", label = "Upload Saved Multilevel Models", accept = c(".rds", ".RDS", ".Rds")),
                               #
                               actionButton("ClearBmlModels", "Delete Saved Multilevel Models"),

                      ),
                      # 
                      hr()
                    ))),
                  mainPanel(
                    fluidRow(
                      tabsetPanel(id = "mainTabset",
                                  tabPanel("Explanation", 
                                           printButton,
                                           h3("Welcome to the interactive living meta-analysis tool!"), 
                                           h4("Purpose:"),
                                           p("The goals of this project are to make it easier to conduct an updatable meta-analysis", 
                                             "and to encourage meta-analysts to present their work as living, evolving states of", 
                                             "knowledge rather than as fixed snapshots of the literature at a single point in time", 
                                             "and from a single point of view.  Meta-analysts can upload data and interactively set", 
                                             "selection criteria and analysis parameters to produce either a frequentist or Bayesian", 
                                             " meta-analytic estimate of an effect size along with standard statistics and graphs.  ", 
                                             "Other researchers can alter the parameters of the analysis or change which studies are ", 
                                             "included and observe the results.", "For reproducibility, R code or R markdown can be",
                                             "downloaded for the selected analysis."), 
                                           h4("Updating Results:"),
                                           p('Most results tabs are updated only when the "(Re)Calculate Meta-Analysis" button is pressed.',
                                             "It is not necessary to re-calculate for each tab, however: all tabs are updated after each recalculation.",
                                             'The exceptions, which always reflect the current data and selections immediately, are the',
                                             '"Current data" and "Descriptives" tabs and the study counts shown in the "Study criteria" panel.'),

                                           h4("Recommended use:"),
                                           p('Because the calculations for Bayesian models can take',
                                             "a long time for large datasets (and the results of Bayesian and frequentist methods are likely to be similar for large datasets), you may want to first use the frequentist",
                                             "panels before deciding which Bayesian models to run.",
                                             "To avoid starting a slow computation by accident, the Bayesian tabs ask for",
                                             "confirmation before a new model is computed; models that have already been computed",
                                             '(or uploaded in the "Saved Plots and Models" tab) are cached and load without asking.',
                                             "The Bayes Factor Robustness Check panel requires multiple",
                                             "recomputations of the Bayesian model and is VERY slow as a result.",
                                             "You may only want to run it once, on your final selected model.",
                                             "The Bayesian MULTILEVEL tabs have one extra cost: the first multilevel fit in a",
                                             "session also compiles the model (about 1-2 minutes extra); later fits are much faster.",
                                             'For Bayesian analyses of large datasets, it is recommended that you download the app (see the "Code and data" and "Updates" sections below) and run it locally on your own machine for better performance.',
                                             "Some precomputed Bayesian models and robustness plots for the default data set may also be included with the app; those load quickly from the cache without recomputation."
                                           ),
                                           
                                           
                                           
                                           
                                           h4("Curated data files:"),
                                           uiOutput("curatedDataLibrary"),

                                           h4("Adding new studies:"),
                                           p("You can add new effect sizes one at a time using the",
                                             '"Add a Study" tab.  To keep the additions for a later session, download',
                                             '"Current data including added studies" from the "Downloads" tab;',
                                             'that file can be uploaded again in the "Load Data File" tab.'),
                                           p('You can also upload an entirely new data file in the "Load Data File" tab.',
                                             "This will replace the current data entirely, including anything that was",
                                             "previously input through the", '"Add a Study" tab.',
                                             "The file to upload should be .csv (with UTF-8 encoding if it contains non-ASCII characters), .xls or .xlsx format.",
                                             "It must contain the following columns (all are required except where marked optional):"),
                                           tags$ul(
                                             tags$li(tags$b("yi"), "- a standardized effect size (Hedges g)"),
                                             tags$li(tags$b("vi"), "- the variance of g"),
                                             tags$li(tags$b("ID"), "- a unique number for each effect size"),
                                             tags$li(tags$b("Paper.Number"), "- a unique number for each paper (study)"),
                                             tags$li(tags$b("Experiment.Number"), "- within each paper"),
                                             tags$li(tags$b("Effect.Size.Number"), "- within each experiment"),
                                             tags$li(tags$b("Paper"), "- citation such as: Author (year)"),
                                             tags$li(tags$b("Paper.and.Exp"), "- citation plus Experiment and/or Effect Size number"),
                                             tags$li(tags$b("Publication.Year"), "- appears as a slider input in the",
                                                     '"Study criteria" panel for selecting which studies to include.'
                                             ),
                                             tags$li(tags$b("Design"), '- "between" or "within", lower case, no quotes.',
                                                     "Appears as a checkbox input in the",
                                                     '"Study criteria" panel for selecting which studies to include.'
                                             ),
                                             tags$li(tags$b("N_Intervention"), "- number of subjects in the intervention condition"),
                                             tags$li(tags$b("N_Control"), "- number of subjects in the baseline condition"),
                                             tags$li(tags$b("N_Total"), "- sum of N_Intervention and N_Control for between-subjects designs; equal to N_Intervention for within-subjects designs"),
                                             tags$li(tags$b("Begin.Selection.Factors"), "and", tags$b("End.Selection.Factors"),
                                                     "- required marker columns (their contents are ignored);",
                                                     "all columns between these two columns will appear as checkbox inputs in the",
                                                     '"Study criteria" panel for selecting which studies to include.',
                                                     'Each checkbox label shows a live "[n ES, k studies]" count badge for that level',
                                                     "(effect-size rows and distinct studies); the",
                                                     tags$b("Live counts"),
                                                     "toggle at the top of the panel updates the badges to reflect the current filters,",
                                                     "or shows whole-dataset totals when unchecked.",
                                             ),
                                             tags$li(tags$b("Begin.Selection.Numerics"), "and", tags$b("End.Selection.Numerics"),
                                                     "- required marker columns (their contents are ignored);",
                                                     "all columns between these two columns will appear as numeric slider inputs in the",
                                                     '"Study criteria" panel for selecting which studies to include.',
                                                     "Both pairs of marker columns must be present even if no selection variables are placed between them.",
                                             ),
                                             tags$li(tags$b("r"), "(optional) - within-study correlation of outcome measures for within-subjects designs."),
                                             tags$li("Any number of additional columns (that will be ignored)")
                                           ),
                                           p("This", 
                                             a("template file", href = "dataFileTemplate.csv", download = "dataFileTemplate.csv"),
                                             "can be used to help prepare your data for upload."),
                                           #       br(),
                                           h4("Calculation methods:"),
                                           p("Meta-analysis calculations use the R", '"metafor" and "bayesmeta" packages, along with',
                                             "functions adapted from", paste0(first_shiny_meta_paper, " and ", noise_meta_paper, "."),
                                             " Input data for meta-analysis are Hedges' g and the variance of g (yi and vi).",
                                             "When yi and vi are calculated from user input, the following are used:"),
                                           tags$ul(
                                             tags$li("g and g_var input by user: copied directly from user input"),
                                             tags$li("g and g_var computed from d: using functions from", noise_meta_paper),
                                             tags$li("g and g_var computed from means: using R metafor::escalc, measure = "),
                                             tags$ul(
                                               tags$li("SMD - using M1, M2, SD1 and SD2 from a between-subject design"),
                                               tags$li("SMD1 - using M1, M2, and SD2 from a between-subject design"),
                                               tags$li("SMCC - using M1, M2, SD1 and SD2 from a within-subject design"),
                                               tags$li("SMCR - using M1, M2, and SD2 from a within-subject design")
                                             )
                                           ),
                                           p('Papers often contribute several effect sizes.  The STANDARD (two-level) analyses',
                                             'handle this by aggregating them first (the "Aggregate over" setting: ID or Papers).',
                                             'The MULTILEVEL analyses -- always available in their own tabs (Frequentist',
                                             'Multilevel, Bayesian Multilevel, and their Regression tabs) -- instead keep every',
                                             'effect size as its own row and model the nesting directly.  The frequentist',
                                             'multilevel model is the correlated-and-hierarchical-effects (CHE) working model:',
                                             'a three-level model with effect sizes nested in papers (metafor::rma.mv,',
                                             'random = ~ 1 | Paper/ID), the within-paper sampling correlation imputed at 0.5',
                                             '(metafor::vcalc; the same assumption the aggregation makes), and cluster-robust',
                                             'CR2 tests and confidence intervals with Satterthwaite degrees of freedom',
                                             '(metafor::robust with the clubSandwich package; Pustejovsky & Tipton, 2022).',
                                             'The Bayesian multilevel model is its brms/Stan analogue; the other Bayesian tabs',
                                             'are based on the bayesmeta package, which uses the aggregated data.'),
                                           h4("Paper:"),
                                           
                                           ("Allbritton, D., Gómez, P., Angele, B., Vasilev, M., & Perea, M. (2024). Breathing Life Into Meta-Analytic Methods. Journal of Cognition, 7(1): 61, pp. 1–17. DOI:"), 
                                           a("https://doi.org/10.5334/joc.389", href="https://doi.org/10.5334/joc.389", target = "_blank"),
                                           h4("Code and data:"),
                                           ("The R Code and sample dataset for the original app as described in the paper can be found "),
                                           a("here", href="https://github.com/davidallbritton/Breathing_life_into_meta-analysis", target = "_blank"),
                                           ("on GitHub."),
                                           h4("This updated version:"),
                                           p("This is an updated version of the app (v1.3).  Additions since the published version include",
                                             "frequentist and Bayesian meta-regression with a categorical moderator, a Descriptives tab",
                                             "(frequency tables, summary statistics, and crosstabs for the currently selected data),",
                                             "live study counts in the selection criteria, a curated collection of data files,",
                                             "saving/loading of selection settings, and MULTILEVEL analyses: frequentist (CHE) and",
                                             "Bayesian (brms) three-level models with effect sizes nested in papers, each with a",
                                             "moderator-regression variant, in their own always-available tabs alongside the",
                                             "standard aggregated analyses -- the downloadable R code reproduces both families."),
                                           br(),
                                           ("Updated: 2026-07-19"),
                                           h4("Updates:"),
                                           ("Updates and extensions can be found at the OSF project site"),
                                           a("https://osf.io/3zxh2/", href="https://osf.io/3zxh2/", target = "_blank"),
                                           br(), 
                                           h4("Contact:"),
                                           p("The app is maintained by David Allbritton"),
                                           p("Contact/Visit us:"),
                                           a(shiny::actionButton(inputId = "david.allbritton@depaul.edu", 
                                                                 label = "Mail", 
                                                                 icon = icon("envelope", lib = "font-awesome")),
                                             href="mailto:david.allbritton@depaul.edu"),
                                           a(shiny::actionButton(inputId = "website", 
                                                                 label = "Web", 
                                                                 icon = icon("globe", lib = "font-awesome")),
                                             href="https://osf.io/3zxh2/", target = "_blank"),
                                           br(),br(),
                                           h5("Acknowledgments:"),
                                           p("This app adapts and extends the work of",
                                             first_shiny_meta_paper, 
                                             br(),
                                             a(first_shiny_meta_paper_doi, href=first_shiny_meta_paper_doi, target="_blank"),
                                             br(),
                                             a(first_shiny_meta_paper_app, href=first_shiny_meta_paper_app, target="_blank"),
                                           )
                                  ),
                        tabPanel("Included Studies", printButton,
                          h4('This table lists all the studies included by the current selected criteria'),
                          p('(updated only when the "(Re)Calculate Meta-Analysis" button on the left side of the screen is pressed)'),
                          br(),
                          DT::dataTableOutput("studies") %>% withSpinner(type = 6, color = "#3498DB"), br()
                          ),
                        tabPanel("Current data", printButton,
                                 h4('This table displays the current data file plus any added studies'), br(),
                                 DT::dataTableOutput("currentData.display") %>% withSpinner(type = 6, color = "#3498DB"), br()
                        ),
                        tabPanel("Descriptives", value = "descriptives", printButton,
                                 h4("Descriptive statistics for the currently selected data"),
                                 p('These summaries describe the effect sizes currently selected by the',
                                   '"Study criteria" panel and update immediately as the selection changes',
                                   '(no need to press "(Re)Calculate Meta-Analysis").  Counts are effect-size rows (ES) and',
                                   'distinct studies (papers).  Factor levels that are ticked in the',
                                   '"Study criteria" panel always appear in the tables, with zero counts if',
                                   'other criteria exclude all their rows; unticked levels are omitted.'),
                                 uiOutput("descSummaryLine"),
                                 hr(),
                                 uiOutput("descriptivesChooser"),
                                 uiOutput("descriptivesTables"),
                                 hr(),
                                 uiOutput("crosstabChooser"),
                                 hr(),
                                 downloadButton("descriptivesDown", "Download these tables (.xlsx)"), br(), br()
                        ),
                        tabPanel("Outlier check",
                                 printButton,
                                 h4("Boxplot of the selected effect sizes (Hedges' g):"),
                                 p('The boxplot shows the distribution of the effect sizes in the current analysis',
                                   '(updated when "(Re)Calculate Meta-Analysis" is pressed).',
                                   'Potential outliers are drawn as orange diamonds and labeled with their study names.',
                                   'To exclude an outlier from the analysis, untick it under "Include/exclude specific studies"',
                                   'at the bottom of the "Study criteria" panel and re-calculate.'),
                                 plotOutput("boxplot") %>% withSpinner(type = 6, color = "#3498DB")),
                        # insert frequentist tabs here
                        tabPanel("Forest plot", 
                                 printButton, 
                                 h4("Frequentist Forest plot with study weights and 95% confidence intervals (aggregated data):"),
                                 p(tags$small('For the multilevel (unaggregated) version, see the "Frequentist Multilevel" tab.')),
                                 plotOutput("freq_forest") %>% withSpinner(type = 6, color = "#3498DB")
                        ),
                        tabPanel("Funnel plot",
                                 printButton,
                                 h4("Frequentist Funnel plot (aggregated data)"),
                                 p("Funnel plot to assess publication bias.",
                                   tags$small('For the multilevel (unaggregated) version, see the "Frequentist Multilevel" tab.')),
                                 plotOutput("freq_funnel") %>% withSpinner(type = 6, color = "#3498DB")
                        ),
                        
                        tabPanel("Meta-Regression",
                                 uiOutput("metaRegressionOutputUI")
                                 ),

                        tabPanel("Frequentist Multilevel", value = "frequentist_multilevel",
                                 printButton,
                                 h4("Frequentist Multilevel (CHE) Meta-Analysis (effect sizes nested in papers)"),
                                 p('Always computed from the UNaggregated effect sizes -- every effect size',
                                   'is its own row, nested in papers -- regardless of the "Aggregate over"',
                                   'setting, so it can be compared side by side with the standard',
                                   '"Forest plot" tab.  The model is the correlated-and-hierarchical-effects',
                                   '(CHE) working model: metafor::rma.mv with random = ~ 1 | Paper/ID,',
                                   'within-paper sampling correlation imputed at 0.5, and cluster-robust',
                                   '(CR2) confidence intervals.  Updated when "(Re)Calculate Meta-Analysis"',
                                   'is pressed.'),
                                 h4("Forest plot:"),
                                 # height = "auto": the container tracks the renderPlot height,
                                 # so the funnel plot below starts after the (tall) forest
                                 plotOutput("freq_forest_ml", height = "auto") %>% withSpinner(type = 6, color = "#3498DB"),
                                 h4("Funnel plot:"),
                                 p("Funnel plot to assess publication bias."),
                                 plotOutput("freq_funnel_ml") %>% withSpinner(type = 6, color = "#3498DB")
                                 ),
                        tabPanel("Frequentist Multilevel Regression", value = "frequentist_multilevel_regression",
                                 uiOutput("metaRegressionMlOutputUI")
                                 ),

                        tabPanel("Bayesian Meta-Regression", value = "bayesian_meta_regression",
                                 printButton,
                                 h4("Bayesian Meta-Regression"),
                                 p("A Bayesian meta-regression with one categorical moderator, fit with",
                                   "bmr() from the bayesmeta package. Each group's pooled effect is estimated",
                                   "with a 95% credible interval, using the same τ (tau) and μ (mu) priors",
                                   "chosen in the sidebar 'Prior specifications' tab."),
                                 p("Will only be computed if 'Yes' is selected for 'Include Moderator' and a",
                                   "categorical moderator is selected in the 'Moderator Selection' tab."),
                                 p("NOTE: Like the other Bayesian analyses, this model can take a long time to",
                                   "build, so it is only computed after you confirm. Once built, it is cached",
                                   "and will not be recomputed for the same data, priors, and moderator."),
                                 conditionalPanel(
                                   condition = "input.includeModerator == 'Yes'",
                                   textOutput("bmrModeratorLabel"),
                                   h4("Forest plot (per-group posterior estimates):"),
                                   uiOutput("bmrForestUI"), br(),
                                   fluidRow(
                                     column(4, sliderInput("bmrEfac", "Symbol size (efac):",
                                                           min = 0.1, max = 2.0, value = 0.3, step = 0.05)),
                                     column(4, numericInput("bmrForestHeightInput", "Plot height (pixels):",
                                                            value = 1000, min = 200, step = 50))
                                   ),
                                   h4("Marginal posterior summary:"),
                                   p("τ (tau): posterior heterogeneity. Each remaining column is a moderator",
                                     "group's posterior effect (mode, median, mean, sd, and 95% credible interval)."),
                                   verbatimTextOutput("bmrSummary") %>% withSpinner(type = 6, color = "#3498DB")
                                 )
                                 ),

                        tabPanel("Bayesian Forest plot",  value = "bayesian_forest_plot",
                                 printButton, 
                                 h4("Forest plot with 95% credible intervals:"),
                                 plotOutput("forest") %>% withSpinner(type = 6, color = "#3498DB")
                                 ),
                        tabPanel("Bayesian Funnel plot", value = "bayesian_funnel_plot",
                                 printButton,
                                 h4("Funnel plot to assess publication bias:"),
                                 plotOutput("funnel")  %>% withSpinner(type = 6, color = "#3498DB")
                                 ),
                        tabPanel("Bayesian Statistics", value = "bayesian_statistics",
                                 printButton,
                                 h4("Parameters:"),
                                 p("τ (tau): posterior distribution of heterogeneity."),
                                 p("μ (mu): posterior distribution of effect."),
                                 p("θ (theta): 'predictive distribution, that expresses the posterior knowledge about a future observation, i.e., an additional draw θk+1 from the underlying population of studies.' (Röver, 2020, p. 16)."),
                                 ("Statistics are calculated/estimated using the bayesmeta package "), 
                                 a("(Röver, 2020).", href="http://dx.doi.org/10.18637/jss.v093.i06", target = "_blank"),
                                 ("The corresponding github page can be found "),
                                 a("here.", href = "https://github.com/cran/bayesmeta", target = "_blank"), br(),
                                 h4("Bayes factors:"), verbatimTextOutput("bf") %>% withSpinner(type = 6, color = "#3498DB"),
                                 p("Bayes factors are only computed if the priors for τ and μ are proper."), br(),
                                 h4("Marginal posterior summary:"), verbatimTextOutput("summary") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("Maximum-likelihood:"), verbatimTextOutput("ML") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("Joint maximum-a-posteriori:"), verbatimTextOutput("MAP") %>% withSpinner(type = 6, color = "#3498DB")
                                 ),
                        tabPanel("Bayesian Additional plots", value = "bayesian_additional_plots",
                                 printButton,
                                 h4("Joint posterior density of heterogeneity τ and effect μ:"), plotOutput("joint") %>%  withSpinner(type = 6, color = "#3498DB"),
                                 p("Darker shading corresponds to higher probability density."),
                                 p("Red lines indicate (approximate) 2-dimensional credible regions,"),
                                 p("green lines show marginal posterior medians and 95% credible intervals,"),
                                 p("blue lines show conditional posterior mean effect as a function of the heterogeneity along with a 95% interval."),
                                 p("Red cross (+): posterior mode"),
                                 p("Pink cross (x): ML estimate"), br(),
                                 h4("Prior, posterior, & likelihood:"), plotOutput("evupdate") %>% withSpinner(type = 6, color = "#3498DB"), br(),
                                 h4("τ prior distribution:"), plotOutput("taupriorplot") %>% withSpinner(type = 6, color = "#3498DB")
                                 ),
                        tabPanel("Bayes factor robustness check", value = "bayesian_robustness",
                                 printButton,
                                 h4("Bayes Factors over a variety of prior standard deviations:"),
                                 p("Will only be computed if 'Yes' is selected for 'µ Bayes Factor robustness check' and the priors for τ and μ are proper.",),br(),
                                 p("NOTE: The robustness check requires computing multiple bayesmeta models",
                                   "and therefore takes a long time for all but the smallest datasets.",
                                   "You may want to delay this step until after you have decided on your final",
                                   "selections for study criteria and priors."),
                                 conditionalPanel(condition = "input.tauprior == 'uniform' | 
                                                               input.tauprior == 'sqrt' |
                                                               input.tauprior == 'Jeffreys' |
                                                               input.tauprior == 'BergerDeely' | 
                                                               input.tauprior == 'conventional' | 
                                                               input.tauprior == 'DuMouchel' | 
                                                               input.tauprior == 'shrinkage' | 
                                                               input.tauprior == 'I2'",
                                                  textOutput("warning2")),
                                 conditionalPanel(condition = "input.robust == 'Yes'", 
                                                  plotOutput("robustplot") %>% withSpinner(type = 6, color = "#3498DB"),
                                 p("Default: 1.5 (orange horizontal line)"),
                                 p("Narrow: user selected standard deviation / 2"),
                                 p("User: user selected standard deviation"),
                                 p("Wide: user selected standard deviation + 1"),
                                 p("Ultrawide: user selected standard deviation + 2"),
                                 p("Interpretations of Bayes factors are based on Jeffreys (1961) with slight modifications by Lee and Wagenmakers (2013) and should be considered with caution."))
                                 ),
                        tabPanel("Bayesian Multilevel", value = "bayesian_multilevel",
                                 printButton,
                                 h4("Bayesian Multilevel Meta-Analysis (effect sizes nested in papers)"),
                                 p('The Bayesian analogue of the "Frequentist Multilevel" tab:',
                                   'a three-level model in which every effect size is its own observation,',
                                   'true effects vary between papers (τ between) and between effect sizes',
                                   'within a paper (τ within), and the priors come from the',
                                   '"Prior specifications" tab (normal on µ; Half cauchy or Half normal on',
                                   'both τs -- the other τ priors and the improper uniform µ prior are not',
                                   'available here).  Fit with the brms package (Stan / MCMC).'),
                                 p('Always computed from the UNaggregated effect sizes, regardless of the',
                                   '"Aggregate over" setting.  Like the other results tabs, this analysis uses',
                                   'the settings as of the last press of "(Re)Calculate Meta-Analysis"; prior',
                                   'changes take effect at the next recalculation.  For per-group posteriors',
                                   'with a moderator, see the "Bayesian Multilevel Regression" tab.'),
                                 p(tags$b("NOTE:"), "the FIRST multilevel fit in a session also compiles the",
                                   "model (about 1-2 minutes extra); later fits only sample (much faster).",
                                   "Fitted models are cached and can be saved/reloaded in the",
                                   '"Saved Plots and Models" tab.'),
                                 uiOutput("bmlContent") %>% withSpinner(type = 6, color = "#3498DB"),
                                 br()
                                 ),
                        tabPanel("Bayesian Multilevel Regression", value = "bayesian_multilevel_regression",
                                 printButton,
                                 h4("Bayesian Multilevel Meta-Regression (one categorical moderator)"),
                                 p('The same three-level model as the "Bayesian Multilevel" tab, but with',
                                   'cell-means coding for the moderator chosen in the "Moderator Selection"',
                                   'tab: each group gets its own posterior mean and 95% credible interval',
                                   '(paralleling the aggregated "Bayesian Meta-Regression" tab).',
                                   'The overall and moderator models are cached independently, so both can',
                                   'be fitted and inspected side by side.'),
                                 p('Always computed from the UNaggregated effect sizes, regardless of the',
                                   '"Aggregate over" setting.  Requires a moderator selected under "Moderator',
                                   'Selection" and a press of "(Re)Calculate Meta-Analysis"; moderator and',
                                   'prior changes take effect at the next recalculation.'),
                                 p(tags$b("NOTE:"), "the first fit of the moderator model in a session also",
                                   "compiles it (about 1-2 minutes extra); later fits only sample."),
                                 uiOutput("bmlRegContent") %>% withSpinner(type = 6, color = "#3498DB"),
                                 br()
                                 ),
                        tabPanel("Downloads", br(),
                          h4("Download Data and Results"),
                          p("From the currently loaded data file and most recent calculations"), 
                          uiOutput("downloadButtons")
                        ), #end of Downloads tab
                         #    
                        tabPanel("R Code", br(),
                                 p("Download an R script (.R file) or R markdown document (.Rmd file)",
                                   "that will reproduce the analyses and plots as currently calculated",
                                   "by the app. The script includes BOTH analysis families -- the standard",
                                   "(aggregated) analyses and the multilevel ones -- each behind an on/off",
                                   'switch near its section ("run_aggregated", "run_multilevel",',
                                   '"calculate_bma", "calculate_brms"), so one download can reproduce a',
                                   "regular and a multilevel analysis together, whichever aggregation mode",
                                   "the app was in. The HelperFunctions file is also required, and the ",
                                   "data file must be in the same directory.  The default data file ",
                                   "name is ",
                                   '"originalData.xlsx"', "(which can be downloaded from the Downloads tab)",
                                   "but the R code can be changed after downloading to accept any ",
                                   ".xlsx, .xls, or .csv filename.",
                                   "The R code that will be downloaded is displayed below.  If it is",
                                   'not displayed or is not what you expected, you may need to press "(Re)Calculate Meta-Analysis".'
                                   ),
                                 downloadButton("downloadCode", "Download R Code"),
                                 downloadButton("downloadMarkdown", "Download R Markdown"),
                                 downloadButton("download_HelperFunctions", "Download required helper functions"),
                                 verbatimTextOutput("R_code_Output")
                                 ),
                        hr()
                          ) #end of main tabs panel
                        )
                      )
                    )
                )                               
                
